apiVersion: v1
kind: Service
metadata:
  name: tic-tac-toe-backend
spec:
  selector:
    app: tic-tac-toe-backend
  ports:
    - protocol: TCP
      port: {{ .Values.backend.servicePort }}
      targetPort: {{ .Values.backend.servicePort }}
  type: {{ .Values.backend.serviceType }}
