apiVersion: v1
kind: Service
metadata:
  name: tic-tac-toe-backend
spec:
  selector:
    app: tic-tac-toe-backend
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}
