apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-calico-system
  namespace: calico-system
spec:
  podSelector: {}
  ingress:
  - {}
  egress:
  - {}
  policyTypes:
  - Ingress
  - Egress
