# Denies all k8s traffic by default
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-np
  namespace: default
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress