apiVersion: v1
kind: Service
metadata:
  name: tic-tac-toe-frontend
spec:
  selector:
    app: tic-tac-toe-frontend
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.servicePort }}
      targetPort: {{ .Values.frontend.servicePort }}
  type: {{ .Values.frontend.serviceType }}
