# Frontend k8s deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tic-tac-toe-frontend
  labels:
    app: tic-tac-toe-frontend
spec:
  revisionHistoryLimit: 1
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: tic-tac-toe-frontend
  template:
    metadata:
      labels:
        app: tic-tac-toe-frontend
    spec:
      podSecurityContext:
        runAsUser: 1000 # App process inside container runs as User 1000 (non-root)
        runAsGroup: 3000 # App process inside container belongs to Group 3000
        fsGroup: 2000 # All mounted volumes inside pod are owned by Group 2000
        runAsNonRoot: true # App must NOT run as root, Kubernetes enforces this
      containers:
        - name: frontend
          image: {{ .Values.frontend.image }} # Frontend image from values.yaml (updated by GH actions)
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.frontend.containerPort }}
          resources:
            limits:
              cpu: "0.5" # 500 millicores
              memory: "512Mi" # 1/2 GB ram
            requests:
              cpu: "0.2" # 200 millicores
              memory: "256Mi" # 1/4 GB ram
          livenessProbe: # Kubelet sends HTTP GET from node to container ip and port at / (index.html). If not 200, kill and restart container
            httpGet:
              path: /
              port: {{ .Values.frontend.containerPort }}
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe: # Kubelet sends HTTPGET from node to container ip and port at / (index.html). If not 200, stop sending traffic to container
            httpGet:
              path: /
              port: {{ .Values.frontend.containerPort }}
            initialDelaySeconds: 5
            periodSeconds: 5
          securityContext:
              readOnlyRootFilesystem: true # Container linux filesystem is read only
      imagePullSecrets:
        - name: github-container-registry # Reference a Kubernetes Secret for pulling private container images from GitHub Container Registry