# Ingress Controller egress network policy
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: tictactoe-ingress-egress-np
  namespace: ingress-nginx
spec:
  # Spec for ingress-nginx ingress controller
  podSelector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx
  policyTypes:
    - Egress
  egress:
    - ports:
        - port: 80
          protocol: TCP
      to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: default
          podSelector:
            matchLabels:
              app: tic-tac-toe-frontend
    - ports:
        - port: 8000
          protocol: TCP
      to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: default
          podSelector:
            matchLabels:
              app: tic-tac-toe-backend
    - ports:
        - port: 9090
          protocol: TCP
      to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
          podSelector:
            matchLabels:
              app.kubernetes.io/name: prometheus
    - ports:
        - port: 3000
          protocol: TCP
      to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
          podSelector:
            matchLabels:
              app.kubernetes.io/name: grafana