apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tic-tac-toe-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tic-tac-toe-frontend
                port:
                  number: {{ .Values.frontend.servicePort }}
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: tic-tac-toe-backend
                port:
                  number: {{ .Values.backend.servicePort }}
