apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-to-frontend
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: tic-tac-toe-frontend  # Target frontend pods
  policyTypes:
    - Ingress
  ingress:
    - {}  # allow all sources