apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-backend-to-redis
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: redis  # Target Redis pods
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: tic-tac-toe-backend  # Only backend should access Redis
      ports:
        - protocol: TCP
          port: {{ .Values.redis.containerPort}}
