apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-backend-egress-to-services
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: tic-tac-toe-backend
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 192.168.126.0/24
      ports:
        - protocol: TCP
          port: {{ .Values.redis.containerPort}}
