apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-frontend-egress-to-services
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: tic-tac-toe-frontend
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 192.168.126.0/24
    - ports:
        - protocol: TCP
          port: 8000
