# Redis role to read redis password
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: redis-secret-reader
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["redis-secret"]
  verbs: ["get"]
