# Redis k8s secrets
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: default
type: Opaque
data:
  REDIS_HOST: cmVkaXM=  # "redis" base64 encoded
  REDIS_PASSWORD: c3VwZXJzZWNyZXQ=  # "supersecret" base64 encoded