# Binds redis secret reader role with backend service account
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: redis-secret-reader-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: backend-sa
  namespace: default
roleRef:
  kind: Role
  name: redis-secret-reader
  apiGroup: rbac.authorization.k8s.io
