# Ingress Controller egress network policy
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: np-allow-nginx-egress
  namespace: ingress-nginx
spec:
  # Spec for ingress-nginx ingress controller
  podSelector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx
  policyTypes:
    - Egress
  egress:
    # Allow ingress controller egress traffic to any pod IPs in the cluster
    # No external traffic (e.g. google.com)
    - to:
        - ipBlock:
            cidr: 192.168.126.0/24
      ports:
        - protocol: TCP
          port: {{ .Values.frontend.containerPort}}
        - protocol: TCP
          port: {{ .Values.backend.containerPort}}