apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-backend-egress-to-redis
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: tic-tac-toe-backend
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: redis
      ports:
        - protocol: TCP
          port: {{ .Values.redis.containerPort}}
