{
 "title": "TicTacToe",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "🔥 CPU Usage by App Pod (Top 5)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "topk(5, sum by (pod) (\r\n  rate(container_cpu_usage_seconds_total{namespace=\"default\"}[5m])\r\n))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "📦 Memory Usage by App Pod",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod) (\r\n  container_memory_usage_bytes{namespace=\"default\"}\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "🔁 Uptime (Seconds)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, (time() - process_start_time_seconds)) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "🚨 Pod Restarts",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "topk(5, rate(kube_pod_container_status_restarts_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "📊 Node CPU Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by (instance) (\r\n  rate(node_cpu_seconds_total{mode!=\"idle\",mode!=\"iowait\"}[5m])\r\n) * 100\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "🧠 Node Memory Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "⚠️ Pods Not Ready",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{condition=\"false\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "📊 Total API Requests",
   "type": "timeseries",
   "description": "Number of requests per endpoint (e.g., /api/move/{index})",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum by (handler) (increase(http_requests_total[1h]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "🔁 Avg Request Latency per Endpoint",
   "type": "timeseries",
   "description": "Calculates average response time per route",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "avg by (handler) (\r\n  rate(http_request_duration_seconds_sum[5m]) \r\n  / \r\n  rate(http_request_duration_seconds_count[5m])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "⚠ Error Rate (5xx)",
   "type": "stat",
   "description": "Count of internal server errors per route",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (handler) (http_requests_total{status=~\"5..\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "❗ Unhandled Exceptions",
   "type": "stat",
   "description": "Shows which endpoints are throwing exceptions",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (handler) (http_exceptions_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "📦 Avg Request Size",
   "type": "stat",
   "description": "Shows average size of requests (payloads)",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (handler) (\r\n  rate(http_request_size_bytes_sum[5m])\r\n) / \r\nsum by (handler) (\r\n  rate(http_request_size_bytes_count[5m])\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "📤 Avg Response Size",
   "type": "stat",
   "description": "Shows average size of backend responses",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (handler) (\r\n  rate(http_response_size_bytes_sum[5m])\r\n) / \r\nsum by (handler) (\r\n  rate(http_response_size_bytes_count[5m])\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "📊 X to O Win Ratio Over Time",
   "type": "timeseries",
   "description": "Business insight on game popularity",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 51 },
   "targets": [
    { "expr": "sum by(outcome) (wins_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "🟦 Player X Win %",
   "type": "gauge",
   "description": "Visualizes the win ratio between Player X and Player O (X wins / O wins)",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(wins_total{outcome=\"X\"}) / sum(wins_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "🟥 Player O Win %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(wins_total{outcome=\"O\"}) / sum(wins_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "🟨 Draw %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(wins_total{outcome=\"draw\"}) / sum(wins_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "🎮 Total Games",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(wins_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "🟦 Is X favored?",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(wins_total{outcome=\"X\"}) > sum(wins_total{outcome=\"O\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "🧮 Total Resets",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(full_game_resets_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "♻️ Full Game Resets",
   "type": "timeseries",
   "description": "Tracks how often players reset the game — may indicate bugs, frustration, or rage quits.",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "resets/min" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(full_game_resets_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "❌ Invalid Moves Total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 68 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (reason) (rate(invalid_moves_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}