frontend:
  replicaCount: 3
  image: ghcr.io/danielchang2001/devsecops-webapp-frontend:sha-ef583894c75b33ade0b2b8bf77848f8b66867d10
  containerPort: 80
  servicePort: 80
  serviceType: LoadBalancer
backend:
  replicaCount: 2
  image: ghcr.io/danielchang2001/devsecops-webapp-backend:sha-ef583894c75b33ade0b2b8bf77848f8b66867d10
  servicePort: 8000
  serviceType: ClusterIP
ingress:
  host: tic-tac-toe.test
redis:
  replicaCount: 1
  image: redis:7.2-alpine
  containerPort: 6379
  serviceType: ClusterIP
  servicePort: 6379
  targetPort: 6379
