frontend:
  replicaCount: 3
  image: ghcr.io/danielchang2001/devsecops-webapp-frontend:sha-8d4b2dd53763c48d068170583099d9212ea8a68f
  containerPort: 80
  servicePort: 80
  serviceType: ClusterIP
backend:
  replicaCount: 2
  image: ghcr.io/danielchang2001/devsecops-webapp-backend:sha-8d4b2dd53763c48d068170583099d9212ea8a68f
  containerPort: 8000
  servicePort: 8000
  serviceType: ClusterIP
ingress:
  host: tic-tac-toe.local
redis:
  replicaCount: 1
  image: redis:7.2-alpine
  containerPort: 6379
  serviceType: ClusterIP
  servicePort: 6379
  targetPort: 6379
defaultDeny:
  podSelector: {}
