frontend:
  replicaCount: 3
  image: ghcr.io/danielchang2001/devsecops-tictactoe-frontend:sha-523a9cef4832dc0089890f2d943a503e794c860e
  containerPort: 80
  servicePort: 80
  serviceType: ClusterIP
backend:
  replicaCount: 2
  image: ghcr.io/danielchang2001/devsecops-tictactoe-backend:sha-523a9cef4832dc0089890f2d943a503e794c860e
  containerPort: 8000
  servicePort: 8000
  serviceType: ClusterIP
ingress:
  host: tic-tac-toe.local
redis:
  replicaCount: 1
  image: redis:7.2-alpine
  containerPort: 6379
  serviceType: ClusterIP
  servicePort: 6379
  targetPort: 6379
defaultDeny:
  podSelector: {}
