frontend:
  replicaCount: 3
  image: ghcr.io/danielchang2001/devsecops-tictactoe-frontend:sha-9c0b2462712ccb2672ce90d44fda2b98f06e66cd
  containerPort: 80
  servicePort: 80
  serviceType: ClusterIP
backend:
  replicaCount: 2
  image: ghcr.io/danielchang2001/devsecops-tictactoe-backend:sha-9c0b2462712ccb2672ce90d44fda2b98f06e66cd
  containerPort: 8000
  servicePort: 8000
  serviceType: ClusterIP
ingress:
  host: tic-tac-toe.local
redis:
  replicaCount: 1
  image: redis:7.2-alpine
  containerPort: 6379
  serviceType: ClusterIP
  servicePort: 6379
  targetPort: 6379
defaultDeny:
  podSelector: {}
