frontend:
  replicaCount: 3
  image: ghcr.io/danielchang2001/devsecops-tictactoe-frontend:sha-0d0dd0a489382194642c0c1087854631453186a7
  containerPort: 80
  servicePort: 80
  serviceType: ClusterIP
backend:
  replicaCount: 2
  image: ghcr.io/danielchang2001/devsecops-tictactoe-backend:sha-0d0dd0a489382194642c0c1087854631453186a7
  containerPort: 8000
  servicePort: 8000
  serviceType: ClusterIP
ingress:
  host: tic-tac-toe.local
redis:
  replicaCount: 1
  image: redis:7.2-alpine
  containerPort: 6379
  serviceType: ClusterIP
  servicePort: 6379
  targetPort: 6379
defaultDeny:
  podSelector: {}
