frontend:
  replicaCount: 3
  image: ghcr.io/danielchang2001/devsecops-webapp-frontend:sha-80d2b7e0f66667ce0583a2d652a3ac56f15d49fd
  containerPort: 80
  servicePort: 80
  serviceType: LoadBalancer
backend:
  replicaCount: 2
  image: ghcr.io/danielchang2001/devsecops-webapp-backend:sha-80d2b7e0f66667ce0583a2d652a3ac56f15d49fd
  containerPort: 8000
  servicePort: 8000
  serviceType: ClusterIP
ingress:
  host: tic-tac-toe.local
redis:
  replicaCount: 1
  image: redis:7.2-alpine
  containerPort: 6379
  serviceType: ClusterIP
  servicePort: 6379
  targetPort: 6379
defaultDeny:
  podSelector: {}
