frontend:
  replicaCount: 3
  image: ghcr.io/danielchang2001/devsecops-webapp-frontend:sha-1274a5acd4c5912843033966f23cef0fc90e0d2a
  containerPort: 80
  servicePort: 80
  serviceType: LoadBalancer
backend:
  replicaCount: 2
  image: ghcr.io/danielchang2001/devsecops-webapp-backend:sha-1274a5acd4c5912843033966f23cef0fc90e0d2a
  servicePort: 8000
  serviceType: ClusterIP
ingress:
  host: tic-tac-toe.local
redis:
  replicaCount: 1
  image: redis:7.2-alpine
  containerPort: 6379
  serviceType: ClusterIP
  servicePort: 6379
  targetPort: 6379
