frontend:
  replicaCount: 3
  image: ghcr.io/danielchang2001/devsecops-webapp-frontend:sha-c54e2419e18c3c02af8bc87e033e75448a6f1dcc
  containerPort: 80
  servicePort: 80
  serviceType: LoadBalancer
backend:
  replicaCount: 2
  image: ghcr.io/danielchang2001/devsecops-webapp-backend:sha-c54e2419e18c3c02af8bc87e033e75448a6f1dcc
  servicePort: 8000
  serviceType: ClusterIP
ingress:
  host: tic-tac-toe.test
redis:
  replicaCount: 1
  image: redis:7.2-alpine
  containerPort: 6379
  serviceType: ClusterIP
  servicePort: 6379
  targetPort: 6379
