frontend:
  replicaCount: 3
  image: ghcr.io/danielchang2001/devsecops-tictactoe-frontend:sha-3426147cc0a0fa87a9582934156e3d77187ffdf8
  containerPort: 80
  servicePort: 80
  serviceType: ClusterIP
backend:
  replicaCount: 2
  image: ghcr.io/danielchang2001/devsecops-tictactoe-backend:sha-3426147cc0a0fa87a9582934156e3d77187ffdf8
  containerPort: 8000
  servicePort: 8000
  serviceType: ClusterIP
ingress:
  host: tic-tac-toe.local
redis:
  replicaCount: 1
  image: redis:7.2-alpine
  containerPort: 6379
  serviceType: ClusterIP
  servicePort: 6379
  targetPort: 6379
defaultDeny:
  podSelector: {}
