frontend:
  replicaCount: 3
  image: ghcr.io/danielchang2001/devsecops-webapp-frontend:sha-2bfd0f69ed2a4d9e004c78150150a2321f25aa16
  containerPort: 80
  servicePort: 80
  serviceType: ClusterIP
backend:
  replicaCount: 2
  image: ghcr.io/danielchang2001/devsecops-webapp-backend:sha-2bfd0f69ed2a4d9e004c78150150a2321f25aa16
  containerPort: 8000
  servicePort: 8000
  serviceType: ClusterIP
ingress:
  host: tic-tac-toe.local
redis:
  replicaCount: 1
  image: redis:7.2-alpine
  containerPort: 6379
  serviceType: ClusterIP
  servicePort: 6379
  targetPort: 6379
defaultDeny:
  podSelector: {}
