frontend:
  replicaCount: 3
  image: ghcr.io/danielchang2001/devsecops-webapp-frontend:sha-75bcf3a2e10086de2960021b45eecf72a2b901fe
  containerPort: 80
  servicePort: 80
  serviceType: LoadBalancer
backend:
  replicaCount: 2
  image: ghcr.io/danielchang2001/devsecops-webapp-backend:sha-75bcf3a2e10086de2960021b45eecf72a2b901fe
  servicePort: 8000
  serviceType: ClusterIP
ingress:
  host: tic-tac-toe.test
redis:
  replicaCount: 1
  image: redis:7.2-alpine
  containerPort: 6379
  serviceType: ClusterIP
  servicePort: 6379
  targetPort: 6379
