apiVersion: apps/v1
kind: Deployment
metadata:
  name: tic-tac-toe-frontend
  labels:
    app: tic-tac-toe-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tic-tac-toe-frontend
  template:
    metadata:
      labels:
        app: tic-tac-toe-frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/danielchang2001/devsecops-webapp-frontend:sha-8c7f8fada115f57bf520fa035802507a904ad166
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.2"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
      imagePullSecrets:
        - name: github-container-registry
