apiVersion: apps/v1
kind: Deployment
metadata:
  name: tic-tac-toe-frontend
  labels:
    app: tic-tac-toe-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tic-tac-toe-frontend
  template:
    metadata:
      labels:
        app: tic-tac-toe-frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/danielchang2001/devsecops-webapp-frontend:sha-566956d6300dc3cbd319532ad451a8d741e6e8f1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: API_URL
              value: http://tic-tac-toe-backend:8000  # service name of backend
      imagePullSecrets:
        - name: github-container-registry
